#默认使用配置
#spring:
#  profiles:
#    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.hecy.mybatis.bean
  mapperLocations: classpath:mapper/*.xml




#开发配置
spring:
#  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/mytest?serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource